"use client";

import Link from "next/link";
import { AlertCircle, FileText, RefreshCw, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/shared/empty-state";
import { DataQualityBanner, DataRequiredState, dataAvailability } from "@/components/shared/data-quality";
import { useBrief } from "@/lib/queries";
import { ExecutiveSummary } from "./executive-summary";
import { CriticalRisks } from "./critical-risks";
import { RevenueOpportunities } from "./revenue-opportunities";
import { RecommendedActions } from "./recommended-actions";
import { HealthScore } from "./health-score";
import { ExportPdfButton } from "./export-pdf-button";

function Section({
  n,
  title,
  children,
}: {
  n: number;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="border-t border-border pt-8">
      <div className="mb-4 flex items-baseline gap-3">
        <span className="font-serif text-sm text-teal-600 tabular-nums">{String(n).padStart(2, "0")}</span>
        <h2 className="font-serif text-xl font-semibold tracking-tight">{title}</h2>
      </div>
      {children}
    </section>
  );
}

export function BriefReport() {
  const { data, isLoading, isError, error, refetch, isFetching } = useBrief();

  if (isLoading) {
    return (
      <div className="mx-auto max-w-3xl animate-pulse space-y-8">
        <div className="h-10 w-2/3 rounded bg-muted" />
        <div className="h-4 w-1/3 rounded bg-muted" />
        {Array.from({ length: 4 }).map((_, i) => (
          <div key={i} className="space-y-3 border-t border-border pt-8">
            <div className="h-5 w-40 rounded bg-muted" />
            <div className="h-4 w-full rounded bg-muted" />
            <div className="h-4 w-5/6 rounded bg-muted" />
          </div>
        ))}
      </div>
    );
  }

  if (isError) {
    return (
      <EmptyState
        icon={AlertCircle}
        title="Could not generate the brief"
        description={error instanceof Error ? error.message : "Please try again."}
        action={<Button onClick={() => refetch()}>Retry</Button>}
      />
    );
  }

  if (!data?.hasData || !data.brief || !data.analysis) {
    return (
      <EmptyState
        icon={FileText}
        tone="teal"
        title="No brief yet"
        description="Import your business data and Inventra will prepare an executive brief for you."
        action={
          <Button asChild>
            <Link href="/upload">Upload data</Link>
          </Button>
        }
      />
    );
  }

  if (!dataAvailability(data.analysis.dataQuality, "brief").available) {
    return <DataRequiredState dq={data.analysis.dataQuality} feature="brief" />;
  }

  const { brief, analysis } = data;
  const generated = new Date(brief.generatedAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div className="mx-auto max-w-3xl">
      {/* Letterhead */}
      <div className="flex flex-wrap items-start justify-between gap-4 pb-8">
        <div>
          <p className="font-serif text-3xl font-semibold tracking-tight">Business Brief</p>
          <p className="mt-2 text-sm text-muted-foreground">
            Prepared for <span className="font-medium text-foreground">{analysis.business}</span>
            {"  ·  "}
            {generated}
            {"  ·  "}
            <span className="inline-flex items-center gap-1">
              <Sparkles className="size-3.5 text-teal-600" />
              Inventra AI
            </span>
          </p>
          <p className="mt-1 text-xs text-muted-foreground">
            {brief.source === "ai"
              ? "Narrative generated by Inventra AI from your data."
              : "Generated from your data using Inventra's analysis engine."}
          </p>
        </div>
        <div className="flex gap-2 print:hidden">
          <Button variant="ghost" size="icon" onClick={() => refetch()} aria-label="Regenerate">
            <RefreshCw className={isFetching ? "size-4 animate-spin" : "size-4"} />
          </Button>
          <ExportPdfButton
            brief={brief}
            business={analysis.business}
            products={analysis.products}
          />
        </div>
      </div>

      <div className="space-y-8">
        <DataQualityBanner dq={analysis.dataQuality} />
        <Section n={1} title="Executive Summary">
          <ExecutiveSummary text={brief.executiveSummary} />
        </Section>

        <Section n={2} title="Critical Risks">
          <CriticalRisks risks={brief.criticalRisks} />
        </Section>

        <Section n={3} title="Revenue Opportunities">
          <RevenueOpportunities items={brief.revenueOpportunities} />
        </Section>

        <Section n={4} title="Recommended Actions">
          <RecommendedActions actions={brief.recommendedActions} />
        </Section>

        <Section n={5} title="Inventory Health Score">
          <HealthScore
            score={brief.healthScore}
            label={brief.healthLabel}
            explanation={brief.healthExplanation}
          />
        </Section>
      </div>
    </div>
  );
}
