// Inventra AI — client-side PDF export of the Purchase Plan.

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { ProcurementPlanResponse } from "../types";

const TEAL: [number, number, number] = [15, 118, 110]; // #0F766E
const CHARCOAL: [number, number, number] = [17, 24, 39]; // #111827
const MUTED: [number, number, number] = [100, 116, 139];

function money(n: number): string {
  return `$${Math.round(n).toLocaleString()}`;
}

/** jsPDF core fonts are Latin-1 only — swap the math glyphs for ASCII. */
function ascii(s: string): string {
  return s.replace(/×/g, "x").replace(/[−–—]/g, "-").replace(/→/g, "->");
}

export function exportPurchasePlanPdf(plan: ProcurementPlanResponse, business: string) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // Letterhead
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(...CHARCOAL);
  doc.text("Purchase Plan", margin, y);
  y += 20;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  doc.text(`Prepared for ${business}  ·  ${dateStr}  ·  Inventra AI`, margin, y);
  y += 12;
  doc.setDrawColor(...TEAL);
  doc.setLineWidth(1.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 26;

  // Summary paragraph
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  doc.setTextColor(40, 40, 40);
  const summary = ascii(plan.summary.replace(/\*\*/g, ""));
  const lines = doc.splitTextToSize(summary, contentWidth);
  doc.text(lines, margin, y);
  y += lines.length * 14 + 18;

  // KPI line
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...TEAL);
  doc.text(
    `${plan.kpis.productsToReorder} products  ·  ${plan.kpis.criticalOrders} critical  ·  ${money(
      plan.kpis.estimatedPurchaseCost
    )} est. cost  ·  ${money(plan.kpis.revenueProtected)} at-risk revenue covered (30-day projection)`,
    margin,
    y
  );
  y += 20;

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [
      ["Product", "SKU", "Stock", "Daily Sales", "Target", "Calculation", "Qty", "Est. Cost", "Priority", "Reason"],
    ],
    body: plan.plan.map((r) => [
      r.name,
      r.sku ?? "—",
      String(r.stock),
      String(r.explanation.dailySales),
      `${r.targetCoverageDays}d`,
      ascii(r.explanation.formula),
      String(r.suggestedQuantity),
      money(r.estimatedCost),
      r.priority,
      ascii(r.explanation.reason),
    ]),
    headStyles: { fillColor: TEAL, textColor: 255, fontStyle: "bold" },
    bodyStyles: { textColor: CHARCOAL },
    alternateRowStyles: { fillColor: [244, 248, 248] },
    styles: { fontSize: 7.5, cellPadding: 4, overflow: "linebreak" },
    columnStyles: {
      0: { cellWidth: 70 },
      2: { halign: "right" },
      3: { halign: "right" },
      4: { halign: "right" },
      5: { cellWidth: 78, font: "courier" },
      6: { halign: "right", fontStyle: "bold" },
      7: { halign: "right" },
      9: { cellWidth: 96 },
    },
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    const h = doc.internal.pageSize.getHeight();
    doc.text(`Generated by Inventra AI — ${dateStr}`, margin, h - 24);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, h - 24, { align: "right" });
  }

  const stamp = new Date().toISOString().slice(0, 10);
  doc.save(`inventra-purchase-plan-${stamp}.pdf`);
}
