// Inventra AI — client-side PDF export of the Purchase Plan.
//
// jsPDF + jspdf-autotable are dynamically imported (fetched only on click, never
// in the server/build graph). Runs entirely in the browser — no Vercel function.
//
// All text is passed through latinize()/pdfProductName(): the core PDF fonts are
// Latin-1 only, so Khmer is forced to a clean English form. See ./sanitize.ts.

import type { jsPDF } from "jspdf";
import { money } from "../format";
import { latinize, pdfGeneratedOn, pdfProductName, pdfSlug } from "./sanitize";
import type { ProcurementPlanResponse } from "../types";

const TEAL: [number, number, number] = [15, 118, 110]; // #0F766E
const CHARCOAL: [number, number, number] = [17, 24, 39]; // #111827
const MUTED: [number, number, number] = [100, 116, 139];

export async function exportPurchasePlanPdf(
  plan: ProcurementPlanResponse,
  business: string
): Promise<void> {
  const [{ jsPDF }, autoTableMod] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
  ]);
  const autoTable = autoTableMod.default;

  const businessName = latinize(business) || "Your Business";
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const generatedOn = pdfGeneratedOn();

  doc.setProperties({
    title: `Inventra AI Purchase Plan — ${businessName}`,
    subject: `Suggested reorder quantities and purchase cost for ${businessName}`,
    author: "Inventra AI",
    creator: "Inventra AI",
    keywords: "inventra, purchase plan, procurement, reorder, FMCG",
  });

  // Letterhead
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(...CHARCOAL);
  doc.text("Purchase Plan", margin, y);
  y += 20;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  doc.text(`Prepared for ${businessName}  ·  ${generatedOn}  ·  Inventra AI`, margin, y);
  y += 12;
  doc.setDrawColor(...TEAL);
  doc.setLineWidth(1.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 26;

  // Summary paragraph
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  doc.setTextColor(40, 40, 40);
  const summary = latinize(plan.summary.replace(/\*\*/g, ""));
  const lines = doc.splitTextToSize(summary, contentWidth);
  doc.text(lines, margin, y);
  y += lines.length * 14 + 18;

  // KPI line
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...TEAL);
  doc.text(
    `${plan.kpis.productsToReorder} products  ·  ${plan.kpis.criticalOrders} critical  ·  ${money(
      plan.kpis.estimatedPurchaseCost
    )} est. cost  ·  ${money(plan.kpis.revenueProtected)} at-risk revenue covered (30-day projection)`,
    margin,
    y
  );
  y += 20;

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [
      ["Product", "SKU", "Stock", "Daily Sales", "Target", "Calculation", "Qty", "Est. Cost", "Priority", "Reason"],
    ],
    body: plan.plan.map((r) => [
      pdfProductName(r.name, r.canonicalName),
      latinize(r.sku) || "-",
      String(r.stock),
      String(r.explanation.dailySales),
      `${r.targetCoverageDays}d`,
      latinize(r.explanation.formula),
      String(r.suggestedQuantity),
      money(r.estimatedCost),
      r.priority,
      latinize(r.explanation.reason),
    ]),
    headStyles: { fillColor: TEAL, textColor: 255, fontStyle: "bold" },
    bodyStyles: { textColor: CHARCOAL },
    alternateRowStyles: { fillColor: [244, 248, 248] },
    styles: { fontSize: 7.5, cellPadding: 4, overflow: "linebreak" },
    columnStyles: {
      0: { cellWidth: 70 },
      2: { halign: "right" },
      3: { halign: "right" },
      4: { halign: "right" },
      5: { cellWidth: 78, font: "courier" },
      6: { halign: "right", fontStyle: "bold" },
      7: { halign: "right" },
      9: { cellWidth: 96 },
    },
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    const h = doc.internal.pageSize.getHeight();
    doc.text(`Generated by Inventra AI  ·  ${generatedOn}`, margin, h - 24);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, h - 24, { align: "right" });
  }

  const stamp = new Date().toISOString().slice(0, 10);
  doc.save(`inventra-purchase-plan-${pdfSlug(businessName)}-${stamp}.pdf`);
}
