// Inventra AI — read the internal catalog (for /catalog and AI grounding).

import { db } from "../db";
import type { CatalogPayload, CatalogProduct } from "../types";

export async function loadCatalog(): Promise<CatalogPayload> {
  const user = await db.user.findFirst({ orderBy: { createdAt: "asc" } });
  if (!user) {
    return {
      hasData: false,
      products: [],
      productCount: 0,
      categoryCount: 0,
      categories: [],
      brands: [],
    };
  }

  const rows = await db.product.findMany({
    where: { userId: user.id },
    orderBy: [{ category: "asc" }, { name: "asc" }],
  });

  const products: CatalogProduct[] = rows.map((p) => ({
    id: p.id,
    sku: p.sku ?? "",
    productCode: p.productCode,
    name: p.name,
    brand: p.brand,
    category: p.category || "Other",
    confidenceScore: p.confidenceScore ?? 1,
    isAutoGenerated: p.isAutoGenerated,
  }));

  const categories = Array.from(new Set(products.map((p) => p.category))).sort();
  const brands = Array.from(
    new Set(products.map((p) => (p.brand ?? "").trim()).filter(Boolean))
  ).sort();

  return {
    hasData: products.length > 0,
    products,
    productCount: products.length,
    categoryCount: categories.length,
    categories,
    brands,
  };
}
