// Inventra AI — read the internal catalog (for /catalog and AI grounding).

import { db } from "../db";
import { getSnapshot } from "../snapshot";
import type { CatalogPayload, CatalogProduct } from "../types";

export async function loadCatalog(userId: string): Promise<CatalogPayload> {
  const [rows, snap] = await Promise.all([
    db.product.findMany({
      where: { userId },
      orderBy: [{ category: "asc" }, { name: "asc" }],
    }),
    getSnapshot(userId).catch(() => null),
  ]);

  const fmcgById = new Map(
    (snap?.analysis.products ?? []).map((p) => [
      p.id,
      { velocity: p.velocity, recommendation: p.recommendation },
    ])
  );

  const products: CatalogProduct[] = rows.map((p) => ({
    id: p.id,
    sku: p.sku ?? "",
    productCode: p.productCode,
    name: p.name,
    canonicalName: p.canonicalName || p.name,
    aliases: p.aliases ?? [],
    brand: p.brand,
    category: p.category || "Other",
    confidenceScore: p.confidenceScore ?? 1,
    isAutoGenerated: p.isAutoGenerated,
    recognitionMethod: p.recognitionMethod || undefined,
    recognitionReason: p.recognitionReason || undefined,
    velocity: fmcgById.get(p.id)?.velocity,
    recommendation: fmcgById.get(p.id)?.recommendation,
  }));

  const categories = Array.from(new Set(products.map((p) => p.category))).sort();
  const brands = Array.from(
    new Set(products.map((p) => (p.brand ?? "").trim()).filter(Boolean))
  ).sort();

  return {
    hasData: products.length > 0,
    products,
    productCount: products.length,
    categoryCount: categories.length,
    categories,
    brands,
  };
}
