// Inventra AI — seeded FMCG product intelligence for recognition.
// ~200 SKUs common in Cambodian / SEA FMCG trade (distributor, mini-mart, grocery).
// Local-first: most rows resolve here in milliseconds with no AI call.

export const CATEGORIES = [
  "Beverage",
  "Water",
  "Instant Noodles",
  "Dairy",
  "Snacks",
  "Confectionery",
  "Cooking",
  "Canned & Packaged",
  "Coffee & Tea",
  "Personal Care",
  "Baby Care",
  "Household",
  "Health",
  "Tobacco",
  "Other",
] as const;

export type Category = (typeof CATEGORIES)[number];

/** SKU prefixes per category. */
export const CATEGORY_CODES: Record<Category, string> = {
  Beverage: "BEV",
  Water: "WTR",
  "Instant Noodles": "NDL",
  Dairy: "DRY",
  Snacks: "SNK",
  Confectionery: "CFN",
  Cooking: "CKG",
  "Canned & Packaged": "CAN",
  "Coffee & Tea": "CFT",
  "Personal Care": "PCR",
  "Baby Care": "BBY",
  Household: "HHD",
  Health: "HLT",
  Tobacco: "TOB",
  Other: "GEN",
};

export interface KbProduct {
  name: string; // canonical name
  brand: string;
  category: Category;
  aliases?: string[];
}

export const KB_PRODUCTS: KbProduct[] = [
  /* ---------------- Beverage ---------------- */
  { name: "Coca-Cola Original 330ml", brand: "Coca-Cola", category: "Beverage", aliases: ["coca cola 330", "coke 330", "coca-cola 330ml", "coca cola 330ml", "កូកាកូឡា 330ml", "កូកា 330"] },
  { name: "Coca-Cola Original 500ml", brand: "Coca-Cola", category: "Beverage", aliases: ["coca cola 500", "coke 500", "coca-cola 500ml"] },
  { name: "Coca-Cola Original 1.5L", brand: "Coca-Cola", category: "Beverage", aliases: ["coca cola 1.5", "coke 1.5l", "coca-cola 1500ml"] },
  { name: "Coca-Cola Zero", brand: "Coca-Cola", category: "Beverage", aliases: ["coke zero", "coca cola zero", "coca-cola zero sugar"] },
  { name: "Sprite 330ml", brand: "Sprite", category: "Beverage", aliases: ["sprite", "sprite can", "sprite 330"] },
  { name: "Sprite 1.5L", brand: "Sprite", category: "Beverage", aliases: ["sprite 1.5", "sprite 1500ml"] },
  { name: "Fanta Orange 330ml", brand: "Fanta", category: "Beverage", aliases: ["fanta orange", "fanta", "fanta 330"] },
  { name: "Fanta Strawberry 330ml", brand: "Fanta", category: "Beverage", aliases: ["fanta strawberry", "fanta red"] },
  { name: "Schweppes Soda Water", brand: "Schweppes", category: "Beverage", aliases: ["schweppes soda", "soda water"] },
  { name: "Schweppes Tonic", brand: "Schweppes", category: "Beverage", aliases: ["schweppes tonic water", "tonic water"] },
  { name: "Pepsi 330ml", brand: "Pepsi", category: "Beverage", aliases: ["pepsi 330", "pepsi cola 330ml", "ប៉ិបស៊ី 330ml", "ប៉ិបស៊ី"] },
  { name: "Pepsi 1.5L", brand: "Pepsi", category: "Beverage", aliases: ["pepsi 1.5", "pepsi 1500ml"] },
  { name: "Pepsi Black", brand: "Pepsi", category: "Beverage", aliases: ["pepsi black", "pepsi zero"] },
  { name: "7 Up 330ml", brand: "7 Up", category: "Beverage", aliases: ["7up", "seven up", "7 up can"] },
  { name: "Mirinda Orange 330ml", brand: "Mirinda", category: "Beverage", aliases: ["mirinda", "mirinda orange"] },
  { name: "Sting Strawberry", brand: "Sting", category: "Beverage", aliases: ["sting red", "sting strawberry energy", "sting"] },
  { name: "Sting Gold", brand: "Sting", category: "Beverage", aliases: ["sting gold energy", "sting yellow"] },
  { name: "Red Bull", brand: "Red Bull", category: "Beverage", aliases: ["red bull energy", "redbull", "krating daeng"] },
  { name: "Carabao", brand: "Carabao", category: "Beverage", aliases: ["carabao energy", "carabao daeng"] },
  { name: "Shark Energy Drink", brand: "Shark", category: "Beverage", aliases: ["shark energy", "shark stimulation"] },
  { name: "M-150 Energy Drink", brand: "M-150", category: "Beverage", aliases: ["m150", "m-150", "m 150"] },
  { name: "Lipo Energy Drink", brand: "Lipo", category: "Beverage", aliases: ["lipo energy"] },
  { name: "Oishi Green Tea Original", brand: "Oishi", category: "Beverage", aliases: ["oishi green tea", "oishi tea"] },
  { name: "Oishi Green Tea Honey Lemon", brand: "Oishi", category: "Beverage", aliases: ["oishi honey lemon"] },
  { name: "Ichitan Green Tea", brand: "Ichitan", category: "Beverage", aliases: ["ichitan", "ichitan tea"] },
  { name: "Birdy Robusta Coffee", brand: "Birdy", category: "Beverage", aliases: ["birdy coffee", "birdy can"] },
  { name: "Nescafe Original Can", brand: "Nescafé", category: "Beverage", aliases: ["nescafe can", "nescafe original can"] },
  { name: "Kopiko Iced Coffee", brand: "Kopiko", category: "Beverage", aliases: ["kopiko coffee drink", "kopiko iced"] },
  { name: "Milo Activ-Go Can", brand: "Milo", category: "Beverage", aliases: ["milo can", "milo drink"] },
  { name: "Tipco Orange Juice", brand: "Tipco", category: "Beverage", aliases: ["tipco juice", "tipco orange"] },
  { name: "Malee Coconut Water", brand: "Malee", category: "Beverage", aliases: ["malee coconut", "coconut water malee"] },
  { name: "DoubleDog Juice", brand: "DoubleDog", category: "Beverage", aliases: ["double dog juice", "doubledog"] },
  { name: "Angkor Beer 330ml", brand: "Angkor", category: "Beverage", aliases: ["angkor beer", "angkor can", "ស្រាបៀរអង្គរ"] },
  { name: "Cambodia Beer 330ml", brand: "Cambodia", category: "Beverage", aliases: ["cambodia beer", "cambodia can"] },
  { name: "Ganzberg Beer", brand: "Ganzberg", category: "Beverage", aliases: ["ganzberg", "ganzberg can"] },
  { name: "Hanuman Beer", brand: "Hanuman", category: "Beverage", aliases: ["hanuman beer"] },
  { name: "Tiger Beer 330ml", brand: "Tiger", category: "Beverage", aliases: ["tiger beer", "tiger can"] },
  { name: "Heineken 330ml", brand: "Heineken", category: "Beverage", aliases: ["heineken beer", "heineken can"] },

  /* ---------------- Water ---------------- */
  { name: "Vital Water 500ml", brand: "Vital", category: "Water", aliases: ["vital 500", "vital 500ml", "vital water 500", "ទឹកសុទ្ធ vital 500ml", "ទឹក vital 500"] },
  { name: "Vital Water 1500ml", brand: "Vital", category: "Water", aliases: ["vital 1500", "vital 1.5l", "vital water 1.5"] },
  { name: "Vital Water 350ml", brand: "Vital", category: "Water", aliases: ["vital 350", "vital small"] },
  { name: "Dasani Water 500ml", brand: "Dasani", category: "Water", aliases: ["dasani", "dasani 500ml", "dasani water"] },
  { name: "Dasani Water 1.5L", brand: "Dasani", category: "Water", aliases: ["dasani 1.5", "dasani 1500ml"] },
  { name: "Aquafina Water 500ml", brand: "Aquafina", category: "Water", aliases: ["aquafina", "aquafina 500ml"] },
  { name: "Kulen Water 500ml", brand: "Kulen", category: "Water", aliases: ["kulen water", "eau kulen", "kulen 500", "ទឹកគូលេន"] },
  { name: "Kulen Water 1.5L", brand: "Kulen", category: "Water", aliases: ["kulen 1.5", "eau kulen 1.5l"] },
  { name: "Hanuman Water 500ml", brand: "Hanuman", category: "Water", aliases: ["hanuman water"] },

  /* ---------------- Dairy ---------------- */
  { name: "Anchor UHT Milk 1L", brand: "Anchor", category: "Dairy", aliases: ["anchor milk", "anchor 1l", "anchor uht milk"] },
  { name: "Anchor UHT Milk 200ml", brand: "Anchor", category: "Dairy", aliases: ["anchor milk 200", "anchor small milk"] },
  { name: "Dutch Lady UHT Milk 1L", brand: "Dutch Lady", category: "Dairy", aliases: ["dutch lady milk", "dutch lady 1l"] },
  { name: "Dutch Lady Chocolate Milk", brand: "Dutch Lady", category: "Dairy", aliases: ["dutch lady chocolate", "dutch lady choc"] },
  { name: "Meiji Fresh Milk 946ml", brand: "Meiji", category: "Dairy", aliases: ["meiji milk", "meiji fresh milk"] },
  { name: "Foremost UHT Milk", brand: "Foremost", category: "Dairy", aliases: ["foremost milk"] },
  { name: "Nestle Bear Brand Milk", brand: "Bear Brand", category: "Dairy", aliases: ["bear brand", "bear brand milk", "nestle bear brand"] },
  { name: "Longevity Condensed Milk", brand: "Longevity", category: "Dairy", aliases: ["longevity milk", "condensed milk longevity", "ទឹកដោះគោ longevity"] },
  { name: "Carnation Condensed Milk", brand: "Carnation", category: "Dairy", aliases: ["carnation milk", "carnation condensed"] },
  { name: "Teapot Sweetened Creamer", brand: "Teapot", category: "Dairy", aliases: ["teapot creamer", "teapot milk"] },
  { name: "Dutch Mill Yogurt Drink", brand: "Dutch Mill", category: "Dairy", aliases: ["dutch mill", "dutchmill", "dutch mill yogurt drink"] },
  { name: "Yomost Yogurt Drink", brand: "Yomost", category: "Dairy", aliases: ["yomost", "yomost yogurt"] },
  { name: "Nestle Yogurt", brand: "Nestlé", category: "Dairy", aliases: ["nestle yogurt", "nestle set yogurt"] },

  /* ---------------- Instant Noodles ---------------- */
  { name: "Mama Shrimp Tom Yum", brand: "Mama", category: "Instant Noodles", aliases: ["mama shrimp", "mama tom yum shrimp", "mama prawn", "មីម៉ាម៉ា បង្គា", "ម៉ាម៉ា បង្គា"] },
  { name: "Mama Pork", brand: "Mama", category: "Instant Noodles", aliases: ["mama pork", "mama minced pork"] },
  { name: "Mama Chicken", brand: "Mama", category: "Instant Noodles", aliases: ["mama chicken", "mama moo deng"] },
  { name: "Yum Yum Shrimp", brand: "Yum Yum", category: "Instant Noodles", aliases: ["yum yum shrimp", "yumyum shrimp"] },
  { name: "Yum Yum Chicken", brand: "Yum Yum", category: "Instant Noodles", aliases: ["yum yum chicken"] },
  { name: "Indomie Mi Goreng", brand: "Indomie", category: "Instant Noodles", aliases: ["indomie mi goreng", "indomie goreng", "mi goreng"] },
  { name: "Indomie Chicken", brand: "Indomie", category: "Instant Noodles", aliases: ["indomie chicken", "indomie soto"] },
  { name: "Nissin Cup Noodles Seafood", brand: "Nissin", category: "Instant Noodles", aliases: ["nissin seafood", "nissin cup seafood", "cup noodle seafood"] },
  { name: "Nissin Cup Noodles Chicken", brand: "Nissin", category: "Instant Noodles", aliases: ["nissin chicken", "nissin cup chicken"] },
  { name: "Buldak Carbonara", brand: "Samyang", category: "Instant Noodles", aliases: ["buldak carbonara", "samyang carbonara", "carbonara buldak"] },
  { name: "Buldak Original", brand: "Samyang", category: "Instant Noodles", aliases: ["buldak", "buldak original", "samyang hot chicken", "buldak hot chicken"] },
  { name: "Buldak 2x Spicy", brand: "Samyang", category: "Instant Noodles", aliases: ["buldak 2x", "buldak double spicy", "nuclear buldak"] },
  { name: "Koka Chicken", brand: "Koka", category: "Instant Noodles", aliases: ["koka chicken", "koka noodles chicken"] },
  { name: "Koka Curry", brand: "Koka", category: "Instant Noodles", aliases: ["koka curry"] },
  { name: "MAMEE Chicken", brand: "MAMEE", category: "Instant Noodles", aliases: ["mamee chicken", "mamee monster"] },
  { name: "A-One Instant Noodles", brand: "A-One", category: "Instant Noodles", aliases: ["a one noodles", "a-one", "aone"] },
  { name: "Mi Chiet Beef", brand: "Mi Chiet", category: "Instant Noodles", aliases: ["mi chiet beef", "mee chiet beef", "michiet beef", "មីជាតិ សាច់គោ", "មីជាតិសាច់គោ"] },
  { name: "Mi Chiet Chicken", brand: "Mi Chiet", category: "Instant Noodles", aliases: ["mi chiet chicken", "mee chiet chicken", "michiet chicken", "មីជាតិ សាច់មាន់", "មីជាតិសាច់មាន់"] },

  /* ---------------- Snacks ---------------- */
  { name: "Lay's Classic", brand: "Lay's", category: "Snacks", aliases: ["lays original", "lay's classic", "lays classic", "lays"] },
  { name: "Lay's BBQ", brand: "Lay's", category: "Snacks", aliases: ["lays bbq", "lay's barbecue"] },
  { name: "Lay's Nori Seaweed", brand: "Lay's", category: "Snacks", aliases: ["lays seaweed", "lays nori"] },
  { name: "Pringles Original", brand: "Pringles", category: "Snacks", aliases: ["pringles original", "pringles classic"] },
  { name: "Pringles Sour Cream & Onion", brand: "Pringles", category: "Snacks", aliases: ["pringles sour cream", "pringles sour cream and onion"] },
  { name: "Pringles Hot & Spicy", brand: "Pringles", category: "Snacks", aliases: ["pringles hot spicy", "pringles spicy"] },
  { name: "Oishi Prawn Crackers", brand: "Oishi", category: "Snacks", aliases: ["oishi prawn crackers", "oishi prawn", "oishi"] },
  { name: "Oishi Onion Rings", brand: "Oishi", category: "Snacks", aliases: ["oishi onion rings", "onion rings"] },
  { name: "Nova Multigrain Chips", brand: "Nova", category: "Snacks", aliases: ["nova chips", "nova multigrain"] },
  { name: "Tasto Potato Chips", brand: "Tasto", category: "Snacks", aliases: ["tasto chips", "tasto"] },
  { name: "Piattos Cheese", brand: "Piattos", category: "Snacks", aliases: ["piattos", "piattos cheese"] },
  { name: "Roller Coaster", brand: "Roller Coaster", category: "Snacks", aliases: ["roller coaster", "rollercoaster snack"] },
  { name: "Mister Potato Original", brand: "Mister Potato", category: "Snacks", aliases: ["mister potato", "mr potato chips"] },
  { name: "Jack 'n Jill Chippy", brand: "Jack 'n Jill", category: "Snacks", aliases: ["chippy", "jack n jill chippy"] },
  { name: "Cheetos Cheese", brand: "Cheetos", category: "Snacks", aliases: ["cheetos", "cheetos cheese"] },
  { name: "Doritos Nacho Cheese", brand: "Doritos", category: "Snacks", aliases: ["doritos", "doritos nacho"] },
  { name: "Calbee Prawn Crackers", brand: "Calbee", category: "Snacks", aliases: ["calbee prawn", "calbee"] },
  { name: "Tong Garden Cashew Nuts", brand: "Tong Garden", category: "Snacks", aliases: ["tong garden cashew", "cashew nuts tong garden"] },
  { name: "Koh-Kae Peanuts", brand: "Koh-Kae", category: "Snacks", aliases: ["koh kae peanuts", "kokae peanut"] },

  /* ---------------- Confectionery ---------------- */
  { name: "Oreo Original", brand: "Oreo", category: "Confectionery", aliases: ["oreo", "oreo biscuit", "oreo cookies"] },
  { name: "Oreo Chocolate", brand: "Oreo", category: "Confectionery", aliases: ["oreo chocolate", "oreo choc creme"] },
  { name: "Tiptop Sandwich Biscuit", brand: "Tiptop", category: "Confectionery", aliases: ["tiptop biscuit", "tip top"] },
  { name: "Cream-O Chocolate", brand: "Cream-O", category: "Confectionery", aliases: ["cream o", "creamo chocolate"] },
  { name: "Hup Seng Cream Crackers", brand: "Hup Seng", category: "Confectionery", aliases: ["hup seng crackers", "hup seng cream"] },
  { name: "Julie's Peanut Butter Sandwich", brand: "Julie's", category: "Confectionery", aliases: ["julies peanut butter", "julie's sandwich"] },
  { name: "Munchy's Lexus Biscuit", brand: "Munchy's", category: "Confectionery", aliases: ["munchys lexus", "munchy's biscuit"] },
  { name: "Jacob's Cream Crackers", brand: "Jacob's", category: "Confectionery", aliases: ["jacobs crackers", "jacob's cream"] },
  { name: "Ritz Crackers", brand: "Ritz", category: "Confectionery", aliases: ["ritz", "ritz crackers"] },
  { name: "KitKat 4 Finger", brand: "KitKat", category: "Confectionery", aliases: ["kitkat", "kit kat", "kitkat chocolate"] },
  { name: "Snickers", brand: "Snickers", category: "Confectionery", aliases: ["snickers bar", "snickers chocolate"] },
  { name: "Cadbury Dairy Milk", brand: "Cadbury", category: "Confectionery", aliases: ["cadbury", "dairy milk", "cadbury dairy milk"] },
  { name: "Beng Beng Wafer", brand: "Beng Beng", category: "Confectionery", aliases: ["beng beng", "bengbeng wafer"] },
  { name: "Tango Wafer", brand: "Tango", category: "Confectionery", aliases: ["tango wafer", "tango"] },
  { name: "Loacker Wafer", brand: "Loacker", category: "Confectionery", aliases: ["loacker", "loacker wafer"] },
  { name: "Kinder Bueno", brand: "Kinder", category: "Confectionery", aliases: ["kinder bueno", "bueno"] },
  { name: "Mentos Mint", brand: "Mentos", category: "Confectionery", aliases: ["mentos", "mentos mint candy"] },
  { name: "Alpenliebe Caramel", brand: "Alpenliebe", category: "Confectionery", aliases: ["alpenliebe", "alpenliebe candy"] },
  { name: "Halls Menthol", brand: "Halls", category: "Confectionery", aliases: ["halls", "halls candy", "halls menthol"] },
  { name: "Chupa Chups Lollipop", brand: "Chupa Chups", category: "Confectionery", aliases: ["chupa chups", "lollipop chupa"] },
  { name: "Big Babol Bubble Gum", brand: "Big Babol", category: "Confectionery", aliases: ["big babol", "babol gum"] },
  { name: "Doublemint Gum", brand: "Doublemint", category: "Confectionery", aliases: ["doublemint", "double mint gum"] },
  { name: "Lotte Xylitol Gum", brand: "Lotte", category: "Confectionery", aliases: ["xylitol gum", "lotte xylitol"] },

  /* ---------------- Cooking ---------------- */
  { name: "Jasmine Rice 5kg", brand: "Generic", category: "Cooking", aliases: ["jasmine rice", "rice 5kg", "khao hom mali", "អង្ករ 5kg"] },
  { name: "Neang Malis Rice 10kg", brand: "Neang Malis", category: "Cooking", aliases: ["neang malis", "malis rice", "អង្ករនាងមាលិស"] },
  { name: "Cook Vegetable Oil 1L", brand: "Cook", category: "Cooking", aliases: ["cook oil", "cooking oil 1l", "cook vegetable oil", "ប្រេងឆា cook"] },
  { name: "Meizan Palm Oil 1L", brand: "Meizan", category: "Cooking", aliases: ["meizan oil", "meizan palm oil"] },
  { name: "Sinsin Soy Sauce", brand: "Sinsin", category: "Cooking", aliases: ["sinsin soy sauce", "sin sin soy", "ទឹកស៊ីអ៊ីវ sinsin"] },
  { name: "Angkor Fish Sauce", brand: "Angkor", category: "Cooking", aliases: ["angkor fish sauce", "fish sauce angkor", "ទឹកត្រី"] },
  { name: "Lee Kum Kee Oyster Sauce", brand: "Lee Kum Kee", category: "Cooking", aliases: ["lee kum kee oyster", "oyster sauce lkk", "lkk oyster sauce"] },
  { name: "Maggi Seasoning Sauce", brand: "Maggi", category: "Cooking", aliases: ["maggi sauce", "maggi seasoning"] },
  { name: "Knorr Chicken Stock Cubes", brand: "Knorr", category: "Cooking", aliases: ["knorr cube", "knorr chicken cube", "knorr stock"] },
  { name: "Ajinomoto MSG 500g", brand: "Ajinomoto", category: "Cooking", aliases: ["ajinomoto", "msg ajinomoto", "monosodium glutamate", "បីជេង"] },
  { name: "Sriracha Chili Sauce", brand: "Sriracha", category: "Cooking", aliases: ["sriracha", "chili sauce sriracha"] },
  { name: "Roza Chili Sauce", brand: "Roza", category: "Cooking", aliases: ["roza chili", "roza sauce"] },
  { name: "Mitr Phol White Sugar 1kg", brand: "Mitr Phol", category: "Cooking", aliases: ["mitr phol sugar", "white sugar 1kg", "ស្ករ"] },
  { name: "Iodized Salt 500g", brand: "Generic", category: "Cooking", aliases: ["salt", "iodized salt", "table salt", "អំបិល"] },
  { name: "Wheat Flour 1kg", brand: "Generic", category: "Cooking", aliases: ["flour", "wheat flour", "all purpose flour", "ម្សៅ"] },
  { name: "Mae Ploy Red Curry Paste", brand: "Mae Ploy", category: "Cooking", aliases: ["mae ploy curry", "red curry paste"] },
  { name: "Kewpie Mayonnaise", brand: "Kewpie", category: "Cooking", aliases: ["kewpie mayo", "japanese mayonnaise"] },

  /* ---------------- Canned & Packaged ---------------- */
  { name: "Ligo Sardines in Tomato Sauce", brand: "Ligo", category: "Canned & Packaged", aliases: ["ligo sardines", "sardines ligo", "ត្រីកំប៉ុង ligo"] },
  { name: "555 Sardines", brand: "555", category: "Canned & Packaged", aliases: ["555 sardines", "sardines 555"] },
  { name: "Ayam Brand Sardines", brand: "Ayam Brand", category: "Canned & Packaged", aliases: ["ayam sardines", "ayam brand fish"] },
  { name: "Sealect Tuna in Oil", brand: "Sealect", category: "Canned & Packaged", aliases: ["sealect tuna", "tuna sealect"] },
  { name: "Ayam Brand Tuna", brand: "Ayam Brand", category: "Canned & Packaged", aliases: ["ayam tuna"] },
  { name: "Ma Ling Luncheon Meat", brand: "Ma Ling", category: "Canned & Packaged", aliases: ["ma ling luncheon", "luncheon meat", "pork luncheon"] },
  { name: "Spam Classic", brand: "Spam", category: "Canned & Packaged", aliases: ["spam", "spam luncheon meat"] },
  { name: "Dole Pineapple Slices", brand: "Dole", category: "Canned & Packaged", aliases: ["dole pineapple", "canned pineapple"] },
  { name: "Nespray Instant Milk Powder", brand: "Nespray", category: "Canned & Packaged", aliases: ["nespray", "nespray milk powder", "milk powder nespray"] },
  { name: "Dumex Dugro Milk Powder", brand: "Dumex", category: "Canned & Packaged", aliases: ["dumex dugro", "dugro milk"] },
  { name: "Nestle Koko Krunch", brand: "Nestlé", category: "Canned & Packaged", aliases: ["koko krunch", "koko krunch cereal"] },
  { name: "Kellogg's Corn Flakes", brand: "Kellogg's", category: "Canned & Packaged", aliases: ["corn flakes", "kelloggs corn flakes"] },
  { name: "Skippy Peanut Butter", brand: "Skippy", category: "Canned & Packaged", aliases: ["skippy peanut butter", "peanut butter skippy"] },
  { name: "Smucker's Strawberry Jam", brand: "Smucker's", category: "Canned & Packaged", aliases: ["smuckers jam", "strawberry jam"] },
  { name: "Farmhouse Sandwich Bread", brand: "Farmhouse", category: "Canned & Packaged", aliases: ["farmhouse bread", "sandwich bread"] },

  /* ---------------- Coffee & Tea ---------------- */
  { name: "Nescafe 3-in-1 Original", brand: "Nescafé", category: "Coffee & Tea", aliases: ["nescafe 3in1", "nescafe 3 in 1", "nescafe original sachet", "ណេស្កាហ្វេ 3in1"] },
  { name: "Nescafe Gold", brand: "Nescafé", category: "Coffee & Tea", aliases: ["nescafe gold", "gold coffee"] },
  { name: "Nescafe Classic Jar", brand: "Nescafé", category: "Coffee & Tea", aliases: ["nescafe classic", "nescafe jar"] },
  { name: "G7 3-in-1 Coffee", brand: "G7", category: "Coffee & Tea", aliases: ["g7 coffee", "g7 3in1", "trung nguyen g7"] },
  { name: "Birdy 3-in-1", brand: "Birdy", category: "Coffee & Tea", aliases: ["birdy 3in1", "birdy sachet"] },
  { name: "Kopiko Brown Coffee", brand: "Kopiko", category: "Coffee & Tea", aliases: ["kopiko brown", "kopiko 3in1"] },
  { name: "Super Coffee 3-in-1", brand: "Super", category: "Coffee & Tea", aliases: ["super coffee", "super 3in1"] },
  { name: "Lipton Yellow Label Tea", brand: "Lipton", category: "Coffee & Tea", aliases: ["lipton tea", "lipton yellow label", "lipton tea bags"] },
  { name: "Lipton Lemon Tea Sachet", brand: "Lipton", category: "Coffee & Tea", aliases: ["lipton lemon tea", "lipton ice tea sachet"] },
  { name: "BOH Tea Bags", brand: "BOH", category: "Coffee & Tea", aliases: ["boh tea", "boh tea bags"] },
  { name: "Cambodia Milk Tea Mix", brand: "Cambodia", category: "Coffee & Tea", aliases: ["milk tea mix", "cambodia milk tea", "តែទឹកដោះគោ"] },

  /* ---------------- Personal Care ---------------- */
  { name: "Colgate Total Toothpaste", brand: "Colgate", category: "Personal Care", aliases: ["colgate total", "colgate toothpaste"] },
  { name: "Colgate Maximum Cavity Protection", brand: "Colgate", category: "Personal Care", aliases: ["colgate cavity", "colgate red"] },
  { name: "Closeup Red Hot Toothpaste", brand: "Closeup", category: "Personal Care", aliases: ["closeup red hot", "close up red hot", "closeup toothpaste"] },
  { name: "Sensodyne Toothpaste", brand: "Sensodyne", category: "Personal Care", aliases: ["sensodyne", "sensodyne toothpaste"] },
  { name: "Colgate Toothbrush", brand: "Colgate", category: "Personal Care", aliases: ["colgate toothbrush", "toothbrush colgate"] },
  { name: "Sunsilk Black Shine Shampoo", brand: "Sunsilk", category: "Personal Care", aliases: ["sunsilk black shine", "sunsilk shampoo"] },
  { name: "Clear Anti-Dandruff Shampoo", brand: "Clear", category: "Personal Care", aliases: ["clear shampoo", "clear anti dandruff"] },
  { name: "Head & Shoulders Shampoo", brand: "Head & Shoulders", category: "Personal Care", aliases: ["head and shoulders", "h&s shampoo", "head & shoulders shampoo"] },
  { name: "Pantene Pro-V Shampoo", brand: "Pantene", category: "Personal Care", aliases: ["pantene shampoo", "pantene pro v"] },
  { name: "Dove Nourishing Shampoo", brand: "Dove", category: "Personal Care", aliases: ["dove shampoo", "dove hair"] },
  { name: "Rejoice Shampoo Sachet", brand: "Rejoice", category: "Personal Care", aliases: ["rejoice sachet", "rejoice shampoo"] },
  { name: "Lifebuoy Soap", brand: "Lifebuoy", category: "Personal Care", aliases: ["lifebuoy soap", "lifebuoy bar"] },
  { name: "Lux Soap", brand: "Lux", category: "Personal Care", aliases: ["lux soap", "lux bar soap"] },
  { name: "Safeguard Soap", brand: "Safeguard", category: "Personal Care", aliases: ["safeguard soap", "safeguard bar"] },
  { name: "Protex Soap", brand: "Protex", category: "Personal Care", aliases: ["protex soap"] },
  { name: "Dove Beauty Bar", brand: "Dove", category: "Personal Care", aliases: ["dove soap", "dove beauty bar"] },
  { name: "Rexona Deodorant Roll-On", brand: "Rexona", category: "Personal Care", aliases: ["rexona", "rexona roll on", "rexona deodorant"] },
  { name: "Nivea Deodorant Spray", brand: "Nivea", category: "Personal Care", aliases: ["nivea deo", "nivea deodorant"] },
  { name: "Gillette Blue II Razor", brand: "Gillette", category: "Personal Care", aliases: ["gillette razor", "gillette blue 2"] },
  { name: "Kotex Soft Pads", brand: "Kotex", category: "Personal Care", aliases: ["kotex pads", "kotex sanitary"] },
  { name: "Modess Sanitary Pads", brand: "Modess", category: "Personal Care", aliases: ["modess pads", "modess sanitary"] },
  { name: "Nivea Body Lotion", brand: "Nivea", category: "Personal Care", aliases: ["nivea lotion", "nivea body"] },
  { name: "Pond's Facial Foam", brand: "Pond's", category: "Personal Care", aliases: ["ponds facial foam", "pond's face wash"] },
  { name: "Vaseline Petroleum Jelly", brand: "Vaseline", category: "Personal Care", aliases: ["vaseline", "petroleum jelly"] },
  { name: "Cotton Buds", brand: "Generic", category: "Personal Care", aliases: ["cotton buds", "q-tips", "ear buds"] },

  /* ---------------- Baby Care ---------------- */
  { name: "MamyPoko Pants M", brand: "MamyPoko", category: "Baby Care", aliases: ["mamypoko m", "mamy poko pants", "diaper mamypoko"] },
  { name: "MamyPoko Pants L", brand: "MamyPoko", category: "Baby Care", aliases: ["mamypoko l"] },
  { name: "Pampers Baby Dry M", brand: "Pampers", category: "Baby Care", aliases: ["pampers m", "pampers baby dry", "diaper pampers"] },
  { name: "Huggies Dry Pants L", brand: "Huggies", category: "Baby Care", aliases: ["huggies l", "huggies pants", "diaper huggies"] },
  { name: "Johnson's Baby Powder", brand: "Johnson's", category: "Baby Care", aliases: ["johnsons baby powder", "johnson baby powder"] },
  { name: "Johnson's Baby Shampoo", brand: "Johnson's", category: "Baby Care", aliases: ["johnsons baby shampoo"] },
  { name: "Johnson's Baby Wipes", brand: "Johnson's", category: "Baby Care", aliases: ["johnsons wipes", "baby wipes johnson"] },
  { name: "Pigeon Baby Wipes", brand: "Pigeon", category: "Baby Care", aliases: ["pigeon wipes", "pigeon baby wipes"] },
  { name: "Cerelac Infant Cereal", brand: "Cerelac", category: "Baby Care", aliases: ["cerelac", "cerelac cereal", "baby cereal"] },

  /* ---------------- Household ---------------- */
  { name: "Tide Detergent Powder 1kg", brand: "Tide", category: "Household", aliases: ["tide detergent", "tide powder", "tide washing powder", "សាប៊ូ tide"] },
  { name: "Ariel Detergent Powder 1kg", brand: "Ariel", category: "Household", aliases: ["ariel detergent", "ariel powder", "ariel washing powder"] },
  { name: "Breeze Detergent Powder", brand: "Breeze", category: "Household", aliases: ["breeze detergent", "breeze powder"] },
  { name: "OMO Detergent Powder", brand: "OMO", category: "Household", aliases: ["omo detergent", "omo powder"] },
  { name: "Attack Liquid Detergent", brand: "Attack", category: "Household", aliases: ["attack detergent", "attack liquid"] },
  { name: "Downy Fabric Softener", brand: "Downy", category: "Household", aliases: ["downy", "downy fabric softener"] },
  { name: "Comfort Fabric Softener", brand: "Comfort", category: "Household", aliases: ["comfort softener", "comfort fabric"] },
  { name: "Sunlight Dishwashing Liquid", brand: "Sunlight", category: "Household", aliases: ["sunlight dishwashing liquid", "sunlight dish soap", "sunlight lemon"] },
  { name: "Mama Lemon Dishwashing Liquid", brand: "Mama Lemon", category: "Household", aliases: ["mama lemon", "mama lime dish soap"] },
  { name: "Clorox Bleach", brand: "Clorox", category: "Household", aliases: ["clorox", "bleach clorox"] },
  { name: "Vim Cream Cleaner", brand: "Vim", category: "Household", aliases: ["vim cleaner", "vim cream"] },
  { name: "Glade Air Freshener Spray", brand: "Glade", category: "Household", aliases: ["glade spray", "glade air freshener"] },
  { name: "Ambi Pur Car Freshener", brand: "Ambi Pur", category: "Household", aliases: ["ambi pur", "ambipur"] },
  { name: "Baygon Cockroach Spray", brand: "Baygon", category: "Household", aliases: ["baygon", "baygon insecticide", "cockroach spray"] },
  { name: "Raid Mosquito Spray", brand: "Raid", category: "Household", aliases: ["raid spray", "raid mosquito"] },
  { name: "Jumbo Mosquito Coil", brand: "Jumbo", category: "Household", aliases: ["jumbo coil", "mosquito coil"] },
  { name: "Cellox Facial Tissue", brand: "Cellox", category: "Household", aliases: ["cellox tissue", "facial tissue cellox"] },
  { name: "Pulppy Toilet Roll", brand: "Pulppy", category: "Household", aliases: ["pulppy toilet paper", "toilet roll pulppy"] },
  { name: "Panasonic AA Batteries", brand: "Panasonic", category: "Household", aliases: ["panasonic aa", "aa batteries panasonic"] },
  { name: "Eveready AAA Batteries", brand: "Eveready", category: "Household", aliases: ["eveready aaa", "aaa batteries"] },
  { name: "Cricket Lighter", brand: "Cricket", category: "Household", aliases: ["cricket lighter", "gas lighter"] },
  { name: "Household Candles", brand: "Generic", category: "Household", aliases: ["candles", "white candles", "ទៀន"] },
  { name: "Safety Matches", brand: "Generic", category: "Household", aliases: ["matches", "match box", "ឈើគូស"] },
  { name: "Scotch-Brite Sponge", brand: "Scotch-Brite", category: "Household", aliases: ["scotch brite sponge", "scotch-brite", "scotchbrite scrub"] },
  { name: "Garbage Bags Roll", brand: "Generic", category: "Household", aliases: ["garbage bags", "trash bags", "rubbish bags"] },

  /* ---------------- Health ---------------- */
  { name: "Panadol Paracetamol 500mg", brand: "Panadol", category: "Health", aliases: ["panadol", "paracetamol panadol", "panadol tablets"] },
  { name: "Paracetamol Tablets", brand: "Generic", category: "Health", aliases: ["paracetamol", "acetaminophen", "fever tablets", "ថ្នាំបំបាត់ក្តៅ"] },
  { name: "Tiger Balm White", brand: "Tiger Balm", category: "Health", aliases: ["tiger balm", "tiger balm white", "ថ្នាំលាបខ្លា"] },
  { name: "Salonpas Pain Relief Patch", brand: "Salonpas", category: "Health", aliases: ["salonpas", "salonpas patch", "pain patch"] },
  { name: "Hansaplast Plasters", brand: "Hansaplast", category: "Health", aliases: ["hansaplast", "band aid", "plasters"] },
  { name: "Royal-D ORS Drink Powder", brand: "Royal-D", category: "Health", aliases: ["royal d", "royal-d", "ors powder", "rehydration salts"] },
  { name: "Strepsils Lozenges", brand: "Strepsils", category: "Health", aliases: ["strepsils", "throat lozenges"] },
  { name: "Eno Antacid", brand: "Eno", category: "Health", aliases: ["eno", "eno fruit salt", "antacid"] },
  { name: "Alcohol 70% 500ml", brand: "Generic", category: "Health", aliases: ["rubbing alcohol", "alcohol 70", "isopropyl alcohol"] },
  { name: "Surgical Face Mask", brand: "Generic", category: "Health", aliases: ["face mask", "surgical mask", "ម៉ាស់"] },

  /* ---------------- Tobacco ---------------- */
  { name: "Marlboro Red", brand: "Marlboro", category: "Tobacco", aliases: ["marlboro red", "marlboro", "បារីម៉ាល់បូរ៉ូ"] },
  { name: "Marlboro Gold", brand: "Marlboro", category: "Tobacco", aliases: ["marlboro gold", "marlboro lights"] },
  { name: "ARA Cigarettes", brand: "ARA", category: "Tobacco", aliases: ["ara cigarettes", "ara"] },
  { name: "Alain Delon Cigarettes", brand: "Alain Delon", category: "Tobacco", aliases: ["alain delon", "alain delon cigarettes"] },
  { name: "555 Cigarettes", brand: "555", category: "Tobacco", aliases: ["555 cigarettes", "state express 555"] },
  { name: "Fine Cigarettes", brand: "Fine", category: "Tobacco", aliases: ["fine cigarettes", "fine"] },
];

/** Known brands — from the KB plus common Cambodian FMCG trade brands. */
export const KNOWN_BRANDS: string[] = Array.from(
  new Set([
    ...KB_PRODUCTS.map((p) => p.brand).filter((b) => b !== "Generic"),
    "Nissin", "Yum Yum", "Nestlé", "Nescafé", "Milo", "Ovaltine", "Dutch Lady",
    "Vinamilk", "Angkor", "Cambodia", "Hanuman", "Ganzberg", "Chang", "Heineken",
    "Aquafina", "Kirin", "Number One", "Mirinda", "7 Up", "Sprite", "Lipton",
    "Sunkist", "Marlboro", "Kokomo", "Wonderfarm", "Pigeon", "Enfagrow", "Similac",
    "S-26", "Friso", "Abbott", "Blackmores", "Vicks", "Betadine", "Dettol",
    "Listerine", "Oral-B", "Palmolive", "Zest", "Rejoice", "TRESemmé", "Fa",
    "Axe", "Old Spice", "Nutella", "Milkita", "Chocopie", "Lotte", "Meiji",
    "Glico", "Pocky", "Hi-Chew", "Fisherman's Friend", "Ricola",
  ])
);

/** Keyword → category. First match wins; order matters (specific before general). */
export const CATEGORY_KEYWORDS: [Category, string[]][] = [
  ["Water", ["water", "aqua", "mineral water", "drinking water", "ទឹក"]],
  ["Instant Noodles", ["noodle", "ramen", "instant mi", "mi goreng", "cup noodle", "carbonara", "buldak", "mama", "indomie", "koka", "mamee", "មី"]],
  ["Baby Care", ["diaper", "nappy", "pants m", "pants l", "baby wipes", "baby powder", "baby shampoo", "infant formula", "baby wash", "mamypoko", "pampers", "huggies"]],
  ["Tobacco", ["cigarette", "cigarettes", "rokok", "marlboro", "បារី"]],
  ["Health", ["paracetamol", "acetaminophen", "panadol", "balm", "plaster", "band aid", "ors", "lozenge", "antacid", "alcohol 70", "face mask", "surgical mask", "medicine", "tablet", "ថ្នាំ"]],
  ["Coffee & Tea", ["3in1", "3 in 1", "coffee mix", "instant coffee", "tea bag", "tea bags", "nescafe", "kopiko", "milk tea", "green tea sachet", "តែ", "កាហ្វេ"]],
  ["Canned & Packaged", ["canned", "sardine", "sardines", "tuna", "luncheon", "spam", "milk powder", "cereal", "corn flakes", "peanut butter", "jam", "mayonnaise", "kambong", "កំប៉ុង", "bread"]],
  ["Cooking", ["rice", "cooking oil", "vegetable oil", "palm oil", "soy sauce", "fish sauce", "oyster sauce", "seasoning", "stock cube", "msg", "monosodium", "flour", "sugar", "salt", "curry paste", "chili sauce", " អង្ករ", "ប្រេង", "ស្ករ", "អំបិល", "ទឹកត្រី"]],
  ["Confectionery", ["biscuit", "cookie", "cracker", "wafer", "candy", "chocolate", "gum", "lollipop", "lozenge candy", "mints", "sweets", "choco"]],
  ["Dairy", ["milk", "yogurt", "yoghurt", "cheese", "cream", "condensed milk", "uht", "creamer", "ទឹកដោះគោ"]],
  ["Personal Care", ["shampoo", "soap", "toothpaste", "toothbrush", "lotion", "deodorant", "conditioner", "sanitary", "pads", "razor", "face wash", "facial foam", "petroleum jelly", "cotton buds"]],
  ["Household", ["detergent", "washing powder", "dishwash", "dish soap", "fabric softener", "bleach", "sponge", "cleaner", "tissue", "toilet paper", "toilet roll", "trash bag", "garbage bag", "air freshener", "insecticide", "mosquito", "battery", "batteries", "lighter", "candle", "matches"]],
  ["Snacks", ["chips", "crackers", "snack", "prawn crackers", "potato", "nuts", "popcorn", "pringles", "lay", "seaweed snack"]],
  ["Beverage", ["cola", "coke", "pepsi", "soda", "juice", "energy drink", "energy", "soft drink", "sprite", "fanta", "red bull", "sting", "carabao", "beer", "drink", "rtd", "ភេសជ្ជៈ", "ស្រាបៀរ"]],
];
